[package]
name = "philips_hue_lab"
version = "0.1.0"
edition = "2021"
description = "Experimental CLI tools for Philips Hue ZigBee IoT devices."

[dependencies]
clap = { version = "4.1", features = ["derive"] }
reqwest = "0.12.12"
serde = "1.0.217"
serde_json = "1.0.138"
